import dns from "node:dns/promises";
import net from "node:net";
import {
  assertReceiveOnlyPublicUrl,
  assertSafeOutboundText,
} from "./outbound-guard.js";

function privateAddress(address: string) {
  if (net.isIPv4(address)) {
    const [a, b] = address.split(".").map(Number);
    return (
      a === 10 ||
      a === 127 ||
      a === 0 ||
      (a === 169 && b === 254) ||
      (a === 172 && b >= 16 && b <= 31) ||
      (a === 192 && b === 168)
    );
  }
  const value = address.toLowerCase();
  return (
    value === "::1" ||
    value === "::" ||
    value.startsWith("fc") ||
    value.startsWith("fd") ||
    value.startsWith("fe80:")
  );
}

export function receiveOnlyServerRedirect(raw: string) {
  const url = new URL(raw);
  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    (url.port && url.port !== "443")
  )
    throw new Error("Only credential-free public HTTPS redirects are allowed");
  return url;
}

async function safeUrl(raw: string, serverRedirect = false) {
  // Model/user-provided addresses pass the outbound-data guard. A Location
  // header is generated by the remote server, so re-running the text-leak
  // heuristic on its signed CDN query can create false positives. Redirects
  // still receive every protocol, credential, DNS, and private-IP check below.
  const url = serverRedirect
    ? receiveOnlyServerRedirect(raw)
    : assertReceiveOnlyPublicUrl(raw);
  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    (url.port && url.port !== "443")
  )
    throw new Error("Only public HTTPS pages can be opened");
  if (
    url.hostname === "localhost" ||
    (net.isIP(url.hostname) && privateAddress(url.hostname))
  )
    throw new Error("Private network addresses are blocked");
  const addresses = await dns.lookup(url.hostname, { all: true });
  if (
    !addresses.length ||
    addresses.some((item) => privateAddress(item.address))
  )
    throw new Error("Private network addresses are blocked");
  return url;
}

async function boundedFetch(
  raw: string,
  redirects = 0,
): Promise<{ url: string; text: string }> {
  const url = await safeUrl(raw, redirects > 0);
  const response = await fetch(url, {
    redirect: "manual",
    headers: { "user-agent": "osCode/0.1 local-assistant" },
    signal: AbortSignal.timeout(12_000),
  });
  if (response.status >= 300 && response.status < 400 && redirects < 3) {
    const location = response.headers.get("location");
    if (!location) throw new Error("Page redirect was invalid");
    return boundedFetch(new URL(location, url).toString(), redirects + 1);
  }
  if (!response.ok) throw new Error(`Page request failed (${response.status})`);
  const type = response.headers.get("content-type") || "";
  if (!/(text\/|application\/(json|xml|xhtml))/i.test(type))
    throw new Error("Only text pages can be opened");
  const body = (await response.text()).slice(0, 750_000);
  return { url: url.toString(), text: body };
}

const MAX_PUBLIC_IMAGE_BYTES = 15 * 1024 * 1024;
const publicImageTypes = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif",
]);

export async function fetchPublicImage(
  raw: string,
  redirects = 0,
): Promise<{ url: string; contentType: string; data: Buffer }> {
  const url = await safeUrl(raw, redirects > 0);
  const response = await fetch(url, {
    redirect: "manual",
    headers: { "user-agent": "osCode/0.2 local-assistant" },
    signal: AbortSignal.timeout(30_000),
  });
  if (response.status >= 300 && response.status < 400 && redirects < 3) {
    const location = response.headers.get("location");
    if (!location) throw new Error("Image redirect was invalid");
    await response.body?.cancel().catch(() => undefined);
    return fetchPublicImage(new URL(location, url).toString(), redirects + 1);
  }
  if (!response.ok || !response.body)
    throw new Error(`Image request failed (${response.status})`);
  const contentType = (response.headers.get("content-type") || "")
    .split(";", 1)[0]
    .trim()
    .toLowerCase();
  if (!publicImageTypes.has(contentType)) {
    await response.body.cancel().catch(() => undefined);
    throw new Error("Only public JPEG, PNG, WebP, or GIF images can be saved");
  }
  const declared = Number(response.headers.get("content-length") || 0);
  if (declared > MAX_PUBLIC_IMAGE_BYTES)
    throw new Error("The public image is larger than 15 MB");
  const reader = response.body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.byteLength;
    if (total > MAX_PUBLIC_IMAGE_BYTES) {
      await reader.cancel().catch(() => undefined);
      throw new Error("The public image is larger than 15 MB");
    }
    chunks.push(value);
  }
  const data = Buffer.concat(
    chunks.map((chunk) => Buffer.from(chunk)),
    total,
  );
  const validSignature =
    (contentType === "image/jpeg" &&
      data.length >= 3 &&
      data[0] === 0xff &&
      data[1] === 0xd8 &&
      data[2] === 0xff) ||
    (contentType === "image/png" &&
      data
        .subarray(0, 8)
        .equals(
          Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
        )) ||
    (contentType === "image/gif" &&
      /^GIF8[79]a/.test(data.toString("ascii", 0, 6))) ||
    (contentType === "image/webp" &&
      data.toString("ascii", 0, 4) === "RIFF" &&
      data.toString("ascii", 8, 12) === "WEBP");
  if (!validSignature)
    throw new Error("The downloaded file did not contain a valid public image");
  return { url: url.toString(), contentType, data };
}

function decodeHtmlAttribute(value: string) {
  return value
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&#x2f;/gi, "/");
}

export function publicImageCandidates(html: string, pageUrl: string) {
  const candidates: string[] = [];
  const add = (raw: string) => {
    try {
      const value = decodeHtmlAttribute(raw.trim());
      if (!value || /^data:/i.test(value)) return;
      const resolved = new URL(value, pageUrl);
      if (resolved.protocol !== "https:") return;
      const url = resolved.toString();
      if (!candidates.includes(url)) candidates.push(url);
    } catch {
      /* Invalid page metadata is ignored. */
    }
  };
  const metadata =
    /<meta\b[^>]*(?:property|name)=["'](?:og:image(?::secure_url)?|twitter:image(?::src)?)["'][^>]*content=["']([^"']+)["'][^>]*>|<meta\b[^>]*content=["']([^"']+)["'][^>]*(?:property|name)=["'](?:og:image(?::secure_url)?|twitter:image(?::src)?)["'][^>]*>/gi;
  for (const match of html.matchAll(metadata)) add(match[1] || match[2] || "");
  const imageSource = /<img\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi;
  for (const match of html.matchAll(imageSource)) {
    if (candidates.length >= 8) break;
    add(match[1] || "");
  }
  return candidates.slice(0, 8);
}

export async function fetchPublicPageImage(raw: string) {
  try {
    return await fetchPublicImage(raw);
  } catch (error) {
    if (!/Only public JPEG, PNG, WebP, or GIF images/i.test(String(error)))
      throw error;
  }
  const page = await boundedFetch(raw);
  const candidates = publicImageCandidates(page.text, page.url);
  for (const candidate of candidates) {
    try {
      return await fetchPublicImage(candidate);
    } catch {
      /* Try the next public image declared by the page. */
    }
  }
  throw new Error(
    "This public page did not expose a safe JPEG, PNG, WebP, or GIF image. Choose another result or a direct image URL.",
  );
}

function plainText(html: string) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

export async function searchWeb(query: string) {
  const q = assertSafeOutboundText(query, "Search query");
  const { text } = await boundedFetch(
    `https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,
  );
  const results: Array<{ title: string; url: string }> = [];
  const expression =
    /<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi;
  for (const match of text.matchAll(expression)) {
    if (results.length >= 8) break;
    let target = match[1].replace(/&amp;/g, "&");
    try {
      const redirect = new URL(target, "https://duckduckgo.com");
      target = redirect.searchParams.get("uddg") || redirect.toString();
      const checked = await safeUrl(target);
      results.push({
        title: plainText(match[2]).slice(0, 180),
        url: checked.toString(),
      });
    } catch {
      /* Unsafe results are omitted. */
    }
  }
  return JSON.stringify(results);
}

export async function fetchWebPage(url: string) {
  const page = await boundedFetch(url.slice(0, 2000));
  return `${page.url}\n\n${plainText(page.text).slice(0, 24_000)}`;
}
